version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT} # Exposing PostgreSQL port to the host machine
    volumes:
      - ./postgres_data:/data  # Mount the volume to the container
    networks:
      - postgres-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 30s
      retries: 3
      timeout: 10s
      start_period: 5s

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000" # S3-compatible API
      - "9001:9001" # MinIO Console (web UI)
    environment:
      MINIO_ROOT_USER:  ${MINIO_USER}        # MinIO access key
      MINIO_ROOT_PASSWORD:  ${MINIO_PASSWORD}   # MinIO secret key
    volumes:
      - ./minio_data:/data                   # Persist MinIO data on host

  app:
    build: ./api-service
    ports:
      - "8080:8080"                           # Expose the API port
    depends_on:
      - minio
    environment:
      MINIO_ENDPOINT: "http://minio:9000"    # Endpoint of MinIO in the compose setup
      MINIO_ACCESS_KEY: ${MINIO_USER}         # MinIO access key
      MINIO_SECRET_KEY: ${MINIO_PASSWORD}         # MinIO secret key

  # # Optional: Your app container here
  # app:
  #   image: your-app-image
  #   container_name: your-app
  #   depends_on:
  #     - db
  #   networks:
  #     - postgres-network
  #   environment:
  #     DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"

networks:
  postgres-network:
    driver: bridge

volumes:
  postgres-data:  # This defines the persistent volume
    driver: local  # Local driver is used by default
