version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT} # Exposing PostgreSQL port to the host machine
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Mount the volume to the container
    networks:
      - postgres-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 30s
      retries: 3
      timeout: 10s
      start_period: 5s

  # # Optional: Your app container here
  # app:
  #   image: your-app-image
  #   container_name: your-app
  #   depends_on:
  #     - db
  #   networks:
  #     - postgres-network
  #   environment:
  #     DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"

networks:
  postgres-network:
    driver: bridge

volumes:
  postgres-data:  # This defines the persistent volume
    driver: local  # Local driver is used by default
