FROM apache/airflow:latest

USER root
RUN sudo apt-get update
RUN sudo apt-get install -y git

USER airflow

# RUN pip install "apache-airflow[celery]==2.10.5" --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.10.5/constraints-3.8.txt"


WORKDIR /opt/airflow/
COPY requirements.txt requirements.txt

RUN python -m pip install --upgrade pip

RUN pip install --user -r requirements.txt

RUN pip install dbt-core
RUN pip install dbt-postgres